apiVersion: v1
kind: Pod
metadata:
  name: test-emptydir-pod
spec:
  containers:
  - image: k8s.gcr.io/busybox
    name: test-emptydir-container
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
