---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-ro
    image: k8s.gcr.io/busybox
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - mountPath: "/mnt"
      name: iscsivol
  volumes:
  - name: iscsivol
    iscsi:
      targetPortal: 192.168.1.31
      iqn: iqn.2020-12.com.example.dnuc01:dnuc01
      initiatorName: iqn.2020-12.com.example.iscsi-server:global-initiator
      lun: 1
      fsType: xfs
      readOnly: false
      chapAuthDiscovery: true
      chapAuthSession: true
      secretRef:
         name: chap-secret
