apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config-09
  namespace: default
data:
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config-09
  namespace: default
data:
  log_level: INFO
